### ISSUE TITLE
Error: Naming collision detected

### ISSUE THREAD

**Issue by OrenElad** [zalmoxisus/remote-redux-devtools#11]
Hi guys,
I did  npm install remote-redux-devtools.
My package.json has: 
  "devDependencies": {
    "react-native-cli": "^0.1.7",
    "remote-redux-devtools": "^0.1.2"
  }
and when I did run react-native start I got the follow collision.
I tried to solved it by remove the inner react folder but it didn't work.
I did npm uninstall and install to that module and to all my modules but it didn't solve it

That is the Error massage:

Error building DependencyGraph:
 Error: Naming collision detected: /Users/oren/Documents/platform-app/node_modules/react-native/node_modules/react/lib/webcomponents.js collides with /Users/oren/Documents/platform-app/node_modules/remote-redux-devtools/node_modules/redux-devtools/node_modules/react/lib/webcomponents.js
    at HasteMap._updateHasteMap (HasteMap.js:132:13)
    at HasteMap.js:103:28
    at tryCallOne (/Users/oren/Documents/platform-app/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
    at /Users/oren/Documents/platform-app/node_modules/react-native/node_modules/promise/lib/core.js:123:15
    at flush (/Users/oren/Documents/platform-app/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)

Please assist
Thanks

**Comment by zalmoxisus** [comment]
Hey,

If you delete `react` folder from ` /Users/oren/Documents/platform-app/node_modules/remote-redux-devtools/node_modules/redux-devtools/node_modules/` does it help?

Which `npm` version do you use? You may check it by running `npm -v`.

**Comment by OrenElad** [comment]
Hi,
Thanks for your quick comment.
I did remove react and react-native start and I got other conflict.
But now I delete the next inner folder and it gone.
Thanks a lot it helped

**Comment by zalmoxisus** [comment]
Could you please let me know which was other conflict folder? And if is possible the version of `npm` and `react-native`.

**Comment by jhen0409** [comment]
@OrenElad are you using npm2?

This has been a vexing problem in npm2 and react-native, so I started using npm3.

**Comment by OrenElad** [comment]
You right I have npm v 2.14.3.
I did some script to remove unused folders
#!/bin/sh

for d in node_modules/* ; do
    rm -rf $d/node_modules/react-native
    rm -rf $d/node_modules/react
done

echo "Removed unused folders"

**Comment by zalmoxisus** [comment]
Didi you really have to remove `react-native` and does it work? I'm confused.

Could you please send also the error you get after removing `/Users/oren/Documents/platform-app/node_modules/remote-redux-devtools/node_modules/redux-devtools/node_modules/` (not from `react-native`)?

**Comment by OrenElad** [comment]
1.
This script remove react-native for other plugins conflict.
I added the react remove for remote-redux-devtools.
2. 
first:
 Error: Naming collision detected: /Users/oren/Documents/platform-app/node_modules/remote-redux-devtools/node_modules/react/node_modules/fbjs/lib/warning.js collides with /Users/oren/Documents/platform-app/node_modules/react-native/node_modules/fbjs/lib/warning.js
second:
 Error: Naming collision detected: /Users/oren/Documents/platform-app/node_modules/remote-redux-devtools/node_modules/redux-devtools/node_modules/react/node_modules/fbjs/lib/toArray.js collides with /Users/oren/Documents/platform-app/node_modules/react-native/node_modules/fbjs/lib/toArray.js

**Comment by zalmoxisus** [comment]
@OrenElad, this one also comes from `react` folder from `/Users/oren/Documents/platform-app/node_modules/remote-redux-devtools/node_modules/redux-devtools/node_modules/`. So, I guess you didn't remove it, but something else. Could you please try removing only `/Users/oren/Documents/platform-app/node_modules/remote-redux-devtools/node_modules/redux-devtools/node_modules/react` to see if it helps.

@jhen0409, I use `npm 2.14.4` and no problems, just checked and reinstalled our [`react-native-counter-ios-android` fork](https://github.com/zalmoxisus/react-native-counter-ios-android).

**Comment by jhen0409** [comment]
@zalmoxisus it can reproduce the problem in react-native@0.19. try [upstream](https://github.com/chentsulin/react-native-counter-ios-android), it also started use remote-redux-devtools.

```
Error building DependencyGraph:
 Error: Naming collision detected: /Users/Jhen/github/react-native-counter-ios-android/node_modules/remote-redux-devtools/node_modules/react/node_modules/fbjs/lib/warning.js collides with /Users/Jhen/github/react-native-counter-ios-android/node_modules/react-native/node_modules/fbjs/lib/warning.js
```

**Comment by zalmoxisus** [comment]
This shouldn't appear anymore starting from `v0.1.7`, as we use `redux-devtools-instrument` now.
