### ISSUE TITLE
remote-redux-devtools doesn't work with latest RN 0.56 release

### ISSUE THREAD

**Issue by todorone** [zalmoxisus/remote-redux-devtools#117]
It doesn't work due to incorrect 'rn-host-detect' behavior. This is similar issue which also has workaround - https://github.com/infinitered/reactotron/issues/724

**Comment by nikolas7892** [comment]
Any ETA on the fix?

**Comment by VicFrolov** [comment]
Yep, same here. Babel 7 issue I presume.

**Comment by LaurieWilliamsNZ** [comment]
Same problem. I've had to remove remote-redux-devtools until this bug is resolved.

**Comment by LaurieWilliamsNZ** [comment]
@todorone is correct. Workaround is to overwrite `node_modules/rn-host-detect.index.js` with https://raw.githubusercontent.com/MaxToyberman/rn-host-detect/35a45bb8424f748f16cc9da0402df144ce11385f/index.js.

It's a messy workaround but at least it's working.

**Comment by SudoPlz** [comment]
I made a PR that should fix the problem above.

Temporarily you can 

1) Run `yarn remove remote-redux-devtools;yarn add remote-redux-devtools-sp`
and

2) Change:
`import devTools from 'remote-redux-devtools';` 
to
`import devTools from 'remote-redux-devtools-sp';`

**Comment by todorone** [comment]
@LaurieWilliamsNZ @SudoPlz Does redux state tracking works for you with above fixes? I somehow see empty redux state tab in React Native Debugger even with both either fixes... 😭

**Comment by jhen0409** [comment]
I've solved the issue by https://github.com/jhen0409/rn-host-detect/pull/5 and published the package as `1.1.4`.

**Comment by todorone** [comment]
@jhen0409 Great, thanks, it's working. The last issue stays is with standalone RNDebugger which doesn't work as redux inspecting tool, while chrome extension do...

**Comment by SudoPlz** [comment]
@todorone I'm using remote-redux-devtools with the npm library I published above and it works, I can inspect my state.

**Comment by MaximWuyts** [comment]
Changing to another Emulator worked for me!
