### ISSUE TITLE
Filter actions out of view

### ISSUE THREAD

**Issue by lifehackett** [zalmoxisus/remote-redux-devtools#13]
I'm using `react-native-router-flux` and for each route change it fires several actions.  Ideally, I'd like to filter out these actions from being displayed in RemoteDev because they create a lot of noise; they'd still fire in the background, but I would prefer not to see them displayed.  I have a similar situation with Sagas.  I came across another library of yours, but it doesn't seem compatible. https://github.com/zalmoxisus/redux-devtools-filter-actions

Do you have any thoughts on how to achieve this?

**Comment by lifehackett** [comment]
Looks like there is already a PR up to address exactly this.

**Comment by zalmoxisus** [comment]
Released in `v0.1.4`. Feel free to reopen the issue if something goes wrong.

**Comment by lifehackett** [comment]
Thanks! I'm a bit concerned that time travel features won't work quite right since the filtered actions never get `socket.emit`ed  as opposed to something that only impacts the display of those actions in the UI which I believe is more in alignment with how your `filter-actions` component works.

**Comment by zalmoxisus** [comment]
Actually, slider monitor should be also wrapped in `filter-actions` monitor (as in [`redux-devtools-extension`](https://github.com/zalmoxisus/redux-devtools-extension)), so it would be the same as here. It would just jump over the filtered actions, but the state would be in tact as we don't filter actions from the devtools instrumentation.
