### ISSUE TITLE
Crashing in react-native when not debugging

### ISSUE THREAD

**Issue by martinchristov** [zalmoxisus/remote-redux-devtools#130]
Running on RN 0.57.7
The following line:
`import { composeWithDevTools } from 'remote-redux-devtools'`

causes the app to crash if remote debugging is not turned on.

![simulator screen shot - iphone 8 - 2018-12-27 at 08 21 44](https://user-images.githubusercontent.com/1336477/50468442-82829200-09b0-11e9-8219-c795d8fbd74b.png)

"your browser does not have a secure random generator. If you don't need unpredictable IDs, you can use nanoid/non-secure"

**Comment by mitziin** [comment]
Same problem here.

**Comment by mitziin** [comment]
A issue was created too at: https://github.com/facebook/react-native/issues/22780

**Comment by mitziin** [comment]
Another user made this fix:
Fix in : index.js in line : 23
change
var _nanoid = require('nanoid/non-secure')

**Comment by vsantana** [comment]
Same here!!!

**Comment by leo1995m** [comment]
Same here

**Comment by VanDevBR** [comment]
Same here. :tired_face:

**Comment by zalmoxisus** [comment]
Can someone check if downgrading to `remote-redux-devtools@0.5.14` fixes the issue?

**Comment by mitziin** [comment]
> Can someone check if downgrading to `remote-redux-devtools@0.5.14` fixes the issue?

Im using the 5.12 version and i have the same issue

**Comment by zalmoxisus** [comment]
@mitziin that's strange, as nanoid was introduced in `0.5.14` last version in https://github.com/zalmoxisus/remotedev-utils/pull/9. Before it was `shortid` and nobody reported such problems.

**Comment by mitziin** [comment]
The 0.5.12 version has a wildcard on the module "remotedev-utils": "^0.1.1".
my npm ls:
─┬ remote-redux-devtools@0.5.12
  └─┬ remotedev-utils@0.1.4
    └─┬ shortid@2.2.14
      └── nanoid@2.0.0

**Comment by zalmoxisus** [comment]
@mitziin you're right. Thanks! It should be fixed in `0.5.16`. I'll update that package as well.

**Comment by mitziin** [comment]
thank you!

**Comment by zalmoxisus** [comment]
@mitziin published `remote-redux-devtools@0.5.16` now, thanks again for the details.
