### ISSUE TITLE
Commit, Sweep, Revert, Reset buttons not working.

### ISSUE THREAD

**Issue by tonis2** [zalmoxisus/remote-redux-devtools#14]
Hei,
I have tried this  on examples and also on my own project, the bug seems to be same.
I am not able to use the ```Commit, Sweep, Revert, Reset``` buttons, on devtools they just wont do anything, tried on App, http://remotedev.io/, and atom-devtools version, nowhere can i use those buttons.

**Comment by zalmoxisus** [comment]
It seems that it was broke in #12. I'll fix it ASAP.

**Comment by zalmoxisus** [comment]
Fixed in `v0.1.5`.
