### ISSUE TITLE
Support `store.dispatch` for handleMessages

### ISSUE THREAD

**Issue by jhen0409** [zalmoxisus/remote-redux-devtools#17]
Currently the [handleMessages](https://github.com/zalmoxisus/remote-redux-devtools/blob/master/src/devTools.js#L41) have `store.liftedStore.dispatch`, it used for devtools. I think we can have behavior of `store.dispatch`. (maybe `APP_DISPATCH`?)

It will can dispatch app action with remotedev-app (it also need to support `APP_DISPATCH` for `store.dispatch`), like this on node REPL:

```js
> const createRemoteStore = require('remotedev-app/lib/store/createRemoteStore').createRemoteStore
> const store = createRemoteStore({ hostname: 'localhost', port: 8000 }, f => f, 'auto')
> store.dispatch({ type: 'xxx' })
```

**Comment by zalmoxisus** [comment]
Yes, I was planning to support that. `APP_DISPATCH ` sounds good to me.
It would be great to implement [`Dispatch Monitor`](https://github.com/YoruNoHikage/redux-devtools-dispatch) starting with custom actions at first (as there would be a lot of changes to send action creators).

**Comment by jhen0409** [comment]
How do you implement `send actionCreators` for` redux-devtools-dispatch`? I think it may be difficult, the actionCreator is possible to use global variables, and the `func` is directly call in [Dispatcher#L104](https://github.com/YoruNoHikage/redux-devtools-dispatch/blob/master/src/Dispatcher.js#L104).

Also, I'm working a CLI tool for simple dispatch, If there is any progress for `APP_DISPATCH` let me know. :)

**Comment by zalmoxisus** [comment]
@jhen0409, agree, I actually said the same above :) That's why I suggested that we'll support only custom actions for now. As custom actions they call the plain objects which you specify manually, in contrast to action creators which can be selected.

What do you think of naming it `ACTION` instead of `APP_DISPATCH`? When an action is dispatched inside the app we already relay a message with the type `ACTION` so it will be the same: a monitor requests an  action.

**Comment by zalmoxisus** [comment]
Added in `v0.1.6`. Will try to implement in the `remote-app` after my PRs for the `dispatch-monitor` are merged.

**Comment by zalmoxisus** [comment]
Added Dispatch monitor in `remotedev-app@0.3.3`. Will add the ability to show/hide the monitor in the next version so, you'll hide it if intend to dispatch actions from elsewhere.
