### ISSUE TITLE
Problem of `isMonitored`

### ISSUE THREAD

**Issue by jhen0409** [zalmoxisus/remote-redux-devtools#22]
I using `redux-persist` with `autoRehydrate` in my project, it will dispatch `persist/REHYDRATE` after `@@INIT`, but [isMonitored](https://github.com/zalmoxisus/remote-redux-devtools/blob/master/src/devTools.js#L135) is `false` at the beginning, so my monitor doesn't receive `persist/REHYDRATE`. (The `START` message is relatively late)

**Comment by zalmoxisus** [comment]
Should be fixed in `v0.2.2`. Please confirm.

If it works, we have to remove `UPDATE` message from `remotedev-app` not to relay the state twice, but it will be a breaking change for those who use `v0.2.0`, so we'll wait a bit with that. I'll keep the issue open till then.

**Comment by jhen0409** [comment]
It works! 👍
