### ISSUE TITLE
devtools monitor is not updating

### ISSUE THREAD

**Issue by tonis2** [zalmoxisus/remote-redux-devtools#24]
My redux app data changes are not being recieved by remote monitor.
It seems this example has the same problem 
http://zalmoxisus.github.io/monitoring/.

console show error with socket connection
![capture](https://cloud.githubusercontent.com/assets/9265556/15013737/3648f65e-120a-11e6-9807-401e1155c89f.JPG)

**Comment by zalmoxisus** [comment]
Could you please also copy the error that you receive in terminal when starting `remotedev --hostname=localhost --port=3000`?

Also please check if you're using the last versions of `remote-redux-devtools`, `remotedev-app`(or other app for monitoring) and `remotedev-server`.

I solved the issue on the server and the example should work. It doesn't seem related to `remotedev-server`.

**Comment by tonis2** [comment]
Got it working by using `devTools({realtime: true})`, 
I guess it should take its value from `proccess.env` but somewhy it didnt get it

**Comment by zalmoxisus** [comment]
Probably you are not setting `process.env.NODE_ENV` to `'development'`. You can use `devTools({ realtime: process.env.NODE_ENV !== 'production' })` if you are sure that will have it set in production. Or keep `devTools({realtime: true})` in case that your are separating production from development in other place.
