### ISSUE TITLE
import not being reflected on device

### ISSUE THREAD

**Issue by vonovak** [zalmoxisus/remote-redux-devtools#27]
Hello,
thanks for this great tool! I'm having a problem with import: I'm running a android 5.1.1. device connected through usb. The chrome extension correctly gets the state changes when they happen and I can go back and forth between them. Export works. But then when start the app anew and import the file exported previously, I get the state changes listed but going between them isn't reflected on the device.

Any idea what could be wrong? I tried this with the remotedev.io as well as the local server. Thank you.

**Comment by zalmoxisus** [comment]
Hey @vonovak,

Sorry for the late response. Just got a chance to check it on the real android device, and it works as intended (moving back and forth, toggling actions, dispatching actions locally and remotely). Tried with [`react-native-counter-ios-android`](https://github.com/chentsulin/react-native-counter-ios-android). Could you give it a try too?

Most likely you there's a problem in your reducers like mutating state or not having "one single source of truth".
