### ISSUE TITLE
remote-redux-devtools not working in genymotion emulator or device

### ISSUE THREAD

**Issue by shawnpanda** [zalmoxisus/remote-redux-devtools#34]
I am hoping to use remote-redux-devtools to help debug a new react native app. However, for some reason, the ```remote redux devtools (chrome extension)``` stopped working and it shows no update. I initially thought it was due to GFW since I am in China and have folllowed the instructions on remotedev-server to establish socket connections through local server ([remotedev-server](https://github.com/zalmoxisus/remotedev-server)). Still, no success.

  In addition, I cloned the [example app](https://github.com/zalmoxisus/react-native-counter-ios-android) and the remote redux devtools doesn't show anything either. Thus, I am confused about the cause of the issue.

  My repo: Its just a simple app that I hope to integrate with firebase [link](https://github.com/shawnpanda/2016-Summer-Of-React-Native/tree/master/Project%2007%20-%20Firebase%20Login)

  Also, I am seeing warnings such as ```TimeoutError {name: "TimeoutError", message: "Event response for 'login' timed out"}``` and ```SocketProtocolError {name: "SocketProtocolError", message: "Client connection establishment timed out", code: 4007}```. (both with remotedev or local server, and in both genymotion emulator and actual device Asus ZenFone 2)

Packages:
"react": "15.2.1",
    "react-native": "^0.30.0",
    "react-native-router-flux": "^3.32.0",
    "react-redux": "^4.4.5",
    "redux": "^3.5.2",
    "redux-logger": "^2.6.1",
    "redux-thunk": "^2.1.0"

Would appreciate any gudiance!
The devtools helped me greatly before!

**Comment by zalmoxisus** [comment]
Thanks for the report. 

[The fork](https://github.com/zalmoxisus/react-native-counter-ios-android) is outdated, you should test @chentsulin's [example](https://github.com/chentsulin/react-native-counter-ios-android). For monitoring you can use @jhen0409's [react-native-debugger](https://github.com/jhen0409/react-native-debugger), which already includes `remotedev-server` and starts it automatically.

Let me know whether it helps.

**Comment by shawnpanda** [comment]
@zalmoxisus Thank you so much! You rock! react-native-debugger worked like a charm. Showed all the state changes in redux and no more yellow warning either.

Closing the issue.
