### ISSUE TITLE
Usage with only basic node

### ISSUE THREAD

**Issue by tristanlievens** [zalmoxisus/remote-redux-devtools#37]
Hi!
I'd love to use remote-devtools for my node application, but I can't seem to make it work. 

Eg. I tried to remote-devtools-ify the most basic example app from the redux repo, and even this one does not seem to connect to my remote-devtools interface. Is it even possible to have remote-devtools work without a browser / React Native interface? 

```javascript
import { createStore } from 'redux'
import devTools from 'remote-redux-devtools'

function counter(state = 0, action) {
  switch (action.type) {
  case 'INCREMENT':
    return state + 1
  case 'DECREMENT':
    return state - 1
  default:
    return state
  }
}

let store = devTools()(createStore)(counter)
store.subscribe(() => console.log(store.getState()))

console.log('Get to your remote devtools application!')
setTimeout(() => store.dispatch({ type: 'INCREMENT' }), 2000)
setTimeout(() => store.dispatch({ type: 'INCREMENT' }), 3000)
setTimeout(() => store.dispatch({ type: 'INCREMENT' }), 4000)
```

It's worth noting that all the examples from this repo work just fine 😄

**Comment by zalmoxisus** [comment]
It used to work, if there are not appeared any issues on `ws` part.

If you could send a pr with a complete example, it would be very useful (to check and to maintain as well). If not, I will try to add one when get some time.

Also note that when a node script ends execution, the session is destroyed and you'll not get anything on the monitor.

**Comment by tristanlievens** [comment]
Done.
