### ISSUE TITLE
Does remote-redux-devtools will be packed to the production bundle？

### ISSUE THREAD

**Issue by feyy** [zalmoxisus/remote-redux-devtools#41]
Thanks for your awsome tools. 
But I  have two questions plaguing:

* We import `remote-redux-devtools` in our js code, So whether it will be packed to the bundle?

* Meanwhile, we install `remote-redux-devtools` in devDependencies, whether it will throw error when run with production dependencies?

**Comment by zalmoxisus** [comment]
By default it shouldn't process anything in production (unless you set `realtime` parameter to `true` or use `sendOn`, `sendOnError`). However, it's you responsibility to remove the code from production if you don't intend to use it there.

A solution would be to have different `configureStore` scripts like [here](https://github.com/gaearon/redux-devtools/blob/master/docs/Walkthrough.md#storeconfigurestorejs-1) or to exclude it right from `configureStore` code:

```js
let enhancer;
if (process.env.NODE_ENV === 'production') {
  enhancer = applyMiddleware(thunk);
} else {
  enhancer = compose(
    applyMiddleware(thunk),
    devTools()
  );
}
```

**Comment by feyy** [comment]
It works ok. But the `remote-redux-devtools` and it's denpendencies will be packed to the production bundle.

**Comment by zalmoxisus** [comment]
You should specify [`NODE_ENV`](https://github.com/gaearon/redux-devtools/blob/master/docs/Walkthrough.md#webpackconfigprodjs), then, in the example above, Webpack via Uglify plugin will remove unused code.

**Comment by feyy** [comment]
Thanks!
