### ISSUE TITLE
secure option isn't used for wss: Websockets

### ISSUE THREAD

**Issue by nrako** [zalmoxisus/remote-redux-devtools#42]
The [`secure` parameter option](https://github.com/zalmoxisus/remote-redux-devtools#parameters) isn't used to set the SocketCluster client options. I'd have expected it would be.

https page end-up with:
```
was not allowed to run insecure content from ws://remotedev.io/socketcluster/.
```

Looking into [the code](https://github.com/zalmoxisus/remote-redux-devtools/blob/5b43f5eff08ac225db688e2c976e3df0e9126963/src/devTools.js#L192) it looks like `secure` is only passed when `port` is defined, but I don't understand why? Is it because remotedev.io doesn't support wss?

**Comment by zalmoxisus** [comment]
> Is it because remotedev.io doesn't support wss?

It didn't support at the beginning, but now it does (thanks to certbot).

Just wondering, should we use that parameter (which was intended for the custom server), or detect client protocol (so will use it only when it's on web page with `https`), or just use always `wss`?

What do you think, are any reasons to still use `ws` for any cases?

**Comment by nrako** [comment]
I see, thanks for the clarification.

I personally don't see any situation were `ws` would be needed.  So I guess I would just always `wss`.

**Comment by zalmoxisus** [comment]
Should work in `v0.4.3`.

**Comment by nrako** [comment]
👍 works great, thanks!
