### ISSUE TITLE
JSON value '1' of type NSNumber cannot be converted to NSString

### ISSUE THREAD

**Issue by tarex** [zalmoxisus/remote-redux-devtools#51]
having this problem with `react-native` version `0.36.0`, i'm using latest `remote-redux-devtools`
<img width="376" alt="screen shot 2016-10-29 at 7 31 14 pm" src="https://cloud.githubusercontent.com/assets/1109422/19829911/a4114f2a-9e0e-11e6-8fcd-6657dacb37f1.png">

used `https://github.com/jhen0409/remote-redux-devtools-on-debugger/`  also

**Comment by zalmoxisus** [comment]
It's hard to tell what's going on here. Is it happening when you start the app or after some actions are dispatched?

Could you try if it works with `remote-redux-devtools@0.5.0`?

**Comment by tarex** [comment]
it's working now, I had also a problem with my store configuration. thanks 👍

**Comment by dasblitz** [comment]
@tarex I'm running into the exact same problem, using` remote-redux-devtools` with `remote-redux-devtools-on-debugger` my configureStore is posted below, could you clarify what steps you took to fix it? Or where I should be looking?

```
import { Platform } from 'react-native';
import { createStore, applyMiddleware, compose } from 'redux';
import createSagaMiddleware from 'redux-saga';
import devTools from 'remote-redux-devtools';

import rootReducer from '../reducers';

// Middleware
import request from '../middleware/request';

const sagaMiddleware = createSagaMiddleware();

/**
* Sets up our store
*
* @return {Object} the redux store object containing the state of our app
*/
export default function configureStore() {
    const enhancer = compose(
        applyMiddleware(thunk, sagaMiddleware),
        devTools({
            name: Platform.OS,
            hostname: 'localhost',
            port: 8084
        })
    );

    const store = {
        ...createStore(rootReducer, enhancer),
        runSaga: sagaMiddleware.run
    };

    // enable hot module replacement on the redux store (module.hot is only available on develop)
    if (module.hot) {
        module.hot.accept(() => {
            const nextRootReducer = require('../reducers/index').default;
            store.replaceReducers(nextRootReducer);
        });
    }

    return store;
}
```

**Comment by zalmoxisus** [comment]
@dasblitz thanks for the details. Maybe if @tarex managed to use it with `remote-redux-devtools-on-debugger`, we could add some details to help others when experiencing such troubles?

**Comment by dasblitz** [comment]
I think that would be great. I'll check tomorrow if deleting and reinstalling all node modules wasn't already enough to fix it.

**Comment by joshfttb** [comment]
I'm having the same problem when starting the app. I'd also be curious for details as to how the others fixed it. Reinstalling node_modules did not work for me.

**Comment by joshfttb** [comment]
I solved this the same way @dasblitz did, but that's not a fix, it's switching to a different tool.

**Comment by carloscuatin** [comment]
I'm having the same problem when starting the app

**Comment by darrencamp** [comment]
This is also happening for me, maybe coincidentally, after updating to MacOS Sierra (10.12.1) and xCode 8.1

react-native: 0.35.0
remote-redux-devtools: 0.5.0
remote-redux-devtools-on-debugger: 0.6.3

**Comment by zalmoxisus** [comment]
Please try to downgrade to `remote-redux-devtools@0.5.0` as in `0.5.1` we updated `socketcluster` which could be the issue. If you can confirm that it fixes that, I'll publish a patch downgrading that lib again.

**Comment by dasblitz** [comment]
@zalmoxisus downgrading to 0.5.0 fixes it for me

**Comment by tarex** [comment]
sorry for the late response, yes just used `0.5.0` but the error message is showing with the latest version. I have checked with newly created react-native app.

**Comment by tarex** [comment]
sorry for the late response, yes just used `0.5.0` but the error message is showing with the latest version. I have checked with the newly created react-native app.

**Comment by zalmoxisus** [comment]
Thanks for the details. Related to https://github.com/SocketCluster/socketcluster-client/issues/67

**Comment by zalmoxisus** [comment]
Could someone try to install `socketcluster-client@5.0.0` to see if it's specific to `5.0.15` patch or to `5.0.0`? It would help to identify where the problem appeared.

**Comment by dasblitz** [comment]
@zalmoxisus yes, I've just installed `"remote-redux-devtools": "0.5.1"` with `socketcluster-client@5.0.0` no errors :)

**Comment by jondubois** [comment]
@dasblitz Can you pinpoint the specific version (or approximate) which breaks it between 0.5.1 and 5.0.15? That way I can narrow down possible issues. I can't test it on my machine.

**Comment by dasblitz** [comment]
@jondubois yes, I tried to make it clear in my previous comment. I get no errors using `socketcluster-client@0.5.0` and `socketcluster-client@0.5.14` (havent tried everything in between), it breaks using `socketcluster-client@0.5.15`

**Comment by zalmoxisus** [comment]
@dasblitz, you confused `remote-redux-devtools` and `socketcluster-client`, or it was a typo and you meant `5.0.0` instead of `0.5.0`?

**Comment by dasblitz** [comment]
Ah my bad it was a typo, updated the version numbers in my comment above

**Comment by zalmoxisus** [comment]
I replicated that. The issue was introduced in the latest patch of `socketcluster-client`. Till a new version is released, just stick to `remote-redux-devtools@0.5.0`.

**Comment by TGPSKI** [comment]
`remote-redux-devtools@0.5.0` works for me! I spent a few days thinking I was going insane tracking this guy down.

**Comment by mmmurf** [comment]
remote-redux-devtools@0.5.0 does not work for me.  I'd be happy to go through detailed troubleshooting steps as this utility is extremely valuable for me. 

Uncommenting devTools() causes the error to occur:
```javascript
function configureStore(initialState) {
  const enhancer = compose(
    applyMiddleware(thunk),
    //devTools()
  );
  return createStore(reducer, initialState, enhancer);
}

const store = configureStore()
```

**Comment by zalmoxisus** [comment]
@mmmurf the same error as in the first post?

**Comment by mmmurf** [comment]
@zalmoxisus yep

**Comment by jondubois** [comment]
@zalmoxisus Ok, after resting on RN on iOS, I can confirm that it was the latest version of SC which was causing the problem. I published the fix to npm in socketcluster-client `v5.0.17`.

**Comment by zalmoxisus** [comment]
@jondubois thanks a lot for investigating this!

**Comment by mmmurf** [comment]
Yes thanks, @jondubois ... works for me now as well.
