### ISSUE TITLE
package.json in v0.5.2 yarn package still refers to socketcluster-client 5.0.14

### ISSUE THREAD

**Issue by andreaswachowski** [zalmoxisus/remote-redux-devtools#55]
I experienced #51 and upgraded from v0.5.1 to v0.5.2 (with `yarn upgrade ...`), but I still got the `JSON value '1' ...` error.

Upon closer inspection, the `package.json` in https://registry.yarnpkg.com/remote-redux-devtools/-/remote-redux-devtools-0.5.2.tgz still includes a reference to socketcluster-client 5.0.14, even though it probably should point to 5.0.17, as seen in https://github.com/zalmoxisus/remote-redux-devtools/blob/master/package.json (and mentioned in #51).

Not sure where such a problem could have been introduced (or whether it is a yarn issue).

**Comment by zalmoxisus** [comment]
@andreaswachowski, just checked it on npm and the `package.json` dependencies are outdated there as well. Should be my fault, though I see it synchronized locally. Should work in `remote-redux-devtools@0.5.3`.

Thanks for the report!

**Comment by andreaswachowski** [comment]
I confirm the dependencies are correct in 0.5.3. Thanks for the blazingly fast response!
