### ISSUE TITLE
Empty Store

### ISSUE THREAD

**Issue by nicolabortignon** [zalmoxisus/remote-redux-devtools#66]
I've tried to add the remote redux devtools,
using the following syntax

`const store = createStore(
  rootReducer,
  composeWithDevTools(
    applyMiddleware(thunk)
  )
)`

(in this [file](https://github.com/PolyStyle/RNFashion/blob/master/app/index.js) ) 
When I start the app, I can see all the console.log logs in the console, but the store (State chart) is empty, the tree is empty, and no action is tracked.
Any advice?

**Comment by zalmoxisus** [comment]
In order to not allow it in production, there's an extra step, see [Enabling](https://github.com/zalmoxisus/remote-redux-devtools#enabling) for more details.

**Comment by nicolabortignon** [comment]
So, I've edited in this way:

`import { composeWithDevTools } from 'remote-redux-devtools';

const appReducer = reducers
const composeEnhancers = composeWithDevTools({ realtime: true, port: 8000 });

function rootReducer (state, action) {
  if (action.type === LOGGING_OUT) {
    state = undefined
  }

  return appReducer(state, action)
}

const store = createStore(
  rootReducer,
  composeEnhancers(
    applyMiddleware(thunk)
  )
)`

And still the state is empty
![screen shot 2017-02-24 at 7 24 57 pm](https://cloud.githubusercontent.com/assets/883459/23315557/fa8fc5ba-fac6-11e6-87b3-8c3f7ecf4f4a.png)

**Comment by zalmoxisus** [comment]
React Native Debugger doesn't use `remote-redux-devtools`. You should use `window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__` instead of our enhancer (`composeWithDevTools`). See [its repo](https://github.com/jhen0409/react-native-debugger) for more details.

**Comment by zalmoxisus** [comment]
In case you want to try `remote-redux-devtools`, just remove the custom `port` option in your code (which implies running a local server) and check https://remotedev.io/local

**Comment by nicolabortignon** [comment]
Perfect, 
so I removed the port, selected Remote Js Debugging from the simulator, 
the standard chrome page opens at http://localhost:8081/debugger-ui and now I can see everything on remotedev.io.


Now, I'ma bit confused on what's the main difference between using this monitor vs using the redux devtool on chrome, or the React Native Debugger. Thoughts on this?

Thanks again for the prompt support!

**Comment by zalmoxisus** [comment]
All three of them use [`remotedev-app`](https://github.com/zalmoxisus/remotedev-app) under the hood, so the implementations are almost identical. The difference is that React Native Debugger also includes an implementation of `remote-redux-devtools`, `remotedev-server`, `react-devtools` and chrome devtools.

**Comment by nicolabortignon** [comment]
Awesome, thanks for the clear explanation, and for the great work!
