### ISSUE TITLE
Security vulnerability in ws module

### ISSUE THREAD

**Issue by FredyC** [zalmoxisus/remote-redux-devtools#67]
Upstream module socketcluster-client needs to be updated first. I have made [PR](https://github.com/SocketCluster/socketcluster-client/pull/76). This is just for tracking it.

**Comment by zalmoxisus** [comment]
@FredyC thanks for the pr and for letting us know! Just to add that `socketcluster-client` uses `ws` module only on node. When using it in browser or React Native, it [uses the native WebSocket](https://github.com/SocketCluster/socketcluster-client/blob/master/lib/ws-browser.js). So, most of cases shouldn't be affected.

**Comment by FredyC** [comment]
Yea, mostly I just wanted to clear out my Snyk report :)

It got merged already, so now just to wait for a new release.
