### ISSUE TITLE
Instances aren't linked like demo.gif

### ISSUE THREAD

**Issue by respectTheCode** [zalmoxisus/remote-redux-devtools#7]
I think I have everything setup correctly but each instance is independent. How do you get the instances to be linked the way they are in the demo.gif?

**Comment by laurent-descrivan** [comment]
I got interested in the project a few weeks ago.

I believe the demo.gif is the short term goal of the project, but my not yet implemented (see the last comment of #2). However, the project seem to be really active, as multi instances was not implemented as of a a few days ago, but is now working.

Big thanks to @zalmoxisus, looks like you are building a great tool for developing redux react native on several devices at the same time. Great time saver!

**Comment by zalmoxisus** [comment]
@respectTheCode, just select the instance which you want to sync other instances, and switch the jumper from "stick" to "sync":
![sync](https://cloud.githubusercontent.com/assets/7957859/12616727/3a7c2ab2-c515-11e5-9bec-e93ad41c67ca.jpg)

@laurent-descrivan, thanks a lot for the feedback!

**Comment by zalmoxisus** [comment]
Sorry, we got a conflict in versions of socketcluster server. Should be fixed now.

**Comment by respectTheCode** [comment]
I had to update everything but its working now.

This is really very cool and is going to save a lot of time. Great work.
