### ISSUE TITLE
with composeWithDevTools, couldn't use 'dispatch' in the action creator.

### ISSUE THREAD

**Issue by royjkim** [zalmoxisus/remote-redux-devtools#70]
I want to know the reason why 'remote-redux-devtools' can't work with 'redux-thunk'.
- I think the reason would be 'compose()' not working in 'composeWithDevTools()'

---

1. not working, 'remote-redux-devtools' with 'redux-thunk'

1-1. When I use 'remote-redux-devtools' with 'redux-thunk', I can't use 'dispatch'.
`const composeEnhancers = composeWithDevTools({ realtime: true })`
`const store = createStore(reducer, composeEnhancers(`
`   applyMiddleware(thunk)`
` ))`

<img width="273" alt="error1" src="https://cloud.githubusercontent.com/assets/18474494/23640467/4cb77960-0331-11e7-8713-98c876c3aabf.png">

1-2. When I use 'remote-redux-devtools' like below, it looks like 'compose()' doesn't work.
`const store = createStore(reducer, composeWithDevTools(`
`  applyMiddleware(thunk)`
`))`

<img width="342" alt="error2" src="https://cloud.githubusercontent.com/assets/18474494/23640665/78150b3a-0332-11e7-8a6f-e12202d08443.png">

2. When I use 'redux-logger' instead of 'remote-redux-devtools', it works fine.
`const logger = createLogger()`
`const store = createStore(reducer, compose(`
`  applyMiddleware(`
`    thunk,`
`    logger`
`  )`
`))`

3. package
"react": "15.4.2",
"react-native": "0.40.0",
"react-redux": "^5.0.3",
"redux": "^3.6.0",
"redux-logger": "^2.8.2",
"redux-thunk": "^2.2.0"

"remote-redux-devtools": "^0.5.7"

**Comment by zalmoxisus** [comment]
It works, you can check it [with our counter example](https://github.com/zalmoxisus/remote-redux-devtools/tree/master/examples/counter). It [applies `redux-thunk` middleware](https://github.com/zalmoxisus/remote-redux-devtools/blob/master/examples/counter/store/configureStore.js#L120 and [`dispatch` works](https://github.com/zalmoxisus/remote-redux-devtools/blob/master/examples/counter/actions/counter.js#L31).

The problem could be that you're importing `composeWithDevTools` not as:
```js
import { composeWithDevTools } from 'remote-redux-devtools';
```
but
```js
import composeWithDevTools from 'remote-redux-devtools';
```

So, you're getting the store enhancer instead.

**Comment by royjkim** [comment]
@zalmoxisus 
Thanks to your quick answer.
I already understood what you want to tell me.
- The difference between `composeWithDevTools` and `{ composeWithDevTools }`.

Anyway, like I said I just want to know the exact reason. (because 'remote-redux-devtools' is cool !). I'll try more things on another projects.

**Comment by lukebarton** [comment]
Also having this issue but only without `{ realtime: true }`
With `{realtime: true}` I get `SocketProtocolError: Socket hung up`

I had it working with the basic enhancer but it would only work 1 out of 3 requests. I guess there's a race condition or something.
