### ISSUE TITLE
Cannot set suppressConnectErrors to false

### ISSUE THREAD

**Issue by nikoskleidis** [zalmoxisus/remote-redux-devtools#84]
When I set suppressConnectErrors to false, this condition:
`suppressConnectErrors = options.suppressConnectErrors ? options.suppressConnectErrors : true;`
sets it back to true
I think it should be:
`suppressConnectErrors = options.suppressConnectErrors !== undefined ? options.suppressConnectErrors : true;`

**Comment by zalmoxisus** [comment]
Yes, it seems that it was missed when changed in https://github.com/zalmoxisus/remote-redux-devtools/commit/886ec92bc864f5288a944f0ad8371d843861e892. /cc @G-Rath

**Comment by G-Rath** [comment]
@nikoskleidis & @zalmoxisus Agreed - Sorry for the mistake, and thanks for the catch :)

**Comment by zalmoxisus** [comment]
Thanks for the fix! It is published as `remote-redux-devtools@0.5.11`.
