### ISSUE TITLE
Remote-redux-devtools doesn't work

### ISSUE THREAD

**Issue by daryn-k** [zalmoxisus/remote-redux-devtools#89]
Remote-redux-devtools doesn't work for server-side rendering app. I did everything according to the documentation! But getting everytime "No store found. Make sure to follow the instructions."

It works well for app without PRELOADED_STATE from server

**Comment by daryn-k** [comment]
I don't know. I didn't touch anything. Devtools started to work after a while.

**Comment by zalmoxisus** [comment]
It was a network issue then, our public server could be overloaded. You can [use a local server](https://github.com/zalmoxisus/remote-redux-devtools#communicate-via-local-server) instead.

**Comment by daryn-k** [comment]
Working with react-redux is worst thing I ever met!

**Comment by Raju10100** [comment]
Right now I am facing the same issue 
Unable to get the window object because it is rendering server side.
Tried to use remote-redux-devtools but it doesn't seem to work for me.

I am linking my store file [here.](url)

**Comment by Raju10100** [comment]
Try using redux-devtools-extension

example:
import logger from 'redux-logger'
import {composeWithDevTools} from 'redux-devtools-extension'

export const history = createMemoryHistory()
const middlewares = [
  thunk,
  routerMiddleware(history),
  logger
]

const store = createStore(
  reducer,
  Map(),
  composeWithDevTools(
    applyMiddleware(...middlewares)
  )
)

export default store
