### ISSUE TITLE
Guidance with native iOS integration. 

### ISSUE THREAD

**Issue by AlexeyDemedetskiy** [zalmoxisus/remote-redux-devtools#92]
Hi! Thank you for putting so much effort in development tooling!

My name is Alexey and I am working on native iOS app with redux-like architecture. 

I need some guidance about how to integrate tooling with purely native code. Without any HS at alll. 

Thanks in advance.

**Comment by zalmoxisus** [comment]
Hey Alexey,

[Here](https://github.com/zalmoxisus/remotedev-server/blob/v0.3/docs/API/Realtime.md) you can find some information about how to integrate it.

You can also take a look at [katanaMonitor-lib-swift](https://github.com/bolismauro/katanaMonitor-lib-swift).

**Comment by AlexeyDemedetskiy** [comment]
Thanks!
